service: waracle

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'test'}
  region: ${opt:region, 'eu-west-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/data
        - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/data/index/*

plugins:
  - serverless-plugin-typescript

package:
  exclude:
    - node_modules/**/*

functions:
  getCakes:
    handler: index.getCakes
    events:
      - http:
          path: cakes
          method: get
          cors: true

  getCakeById:
    handler: index.getCakeById
    events:
      - http:
          path: cakes/{id}
          method: get
          cors: true

  postCake:
    handler: index.postCake
    events:
      - http:
          path: cakes
          method: post
          cors: true

  putCakeById:
    handler: index.putCakeById
    events:
      - http:
          path: cakes/{id}
          method: put
          cors: true

  deleteCakeById:
    handler: index.deleteCakeById
    events:
      - http:
          path: cakes/{id}
          method: delete
          cors: true

resources:
  Resources:
    DataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI-sk
            KeySchema:
              - AttributeName: sk
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        TableName: data
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
